export const QUESTION_FETCH_ALL_REQUEST = 'QUESTION_FETCH_ALL_REQUEST'
export const QUESTION_FETCH_ALL_SUCCESS = 'QUESTION_FETCH_ALL_SUCCESS'
export const QUESTION_FETCH_ALL_FAIL = 'QUESTION_FETCH_ALL_FAIL'

export const QUESTION_SAVE_ANSWER_REQUEST = 'QUESTION_SAVE_ANSWER_REQUEST'
export const QUESTION_SAVE_ANSWER_SUCCESS = 'QUESTION_SAVE_ANSWER_SUCCESS'
export const QUESTION_SAVE_ANSWER_FAIL = 'QUESTION_SAVE_ANSWER_FAIL'

export const QUESTION_SAVE_NEW_REQUEST = 'QUESTION_SAVE_NEW_REQUEST'
export const QUESTION_SAVE_NEW_SUCCESS = 'QUESTION_SAVE_NEW_SUCCESS'
export const QUESTION_SAVE_NEW_FAIL = 'QUESTION_SAVE_NEW_FAIL'
