export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCESS = 'USER_SIGNIN_SUCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'

export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SET_ERROR = 'USER_SET_ERROR'

export const USER_FETCH_ALL_USERS_REQUEST = 'USER_FETCH_ALL_USERS_REQUEST'
export const USER_FETCH_ALL_USERS_SUCCESS = 'USER_FETCH_ALL_USERS_SUCCESS'
export const USER_FETCH_ALL_USERS_FAIL = 'USER_FETCH_ALL_USERS_FAIL'